### ISSUE TITLE
mancato accesso 

### ISSUE THREAD

**Issue by picomiles** [teamdigitale/matrix.developers.italia.it#9]
Salve, ho letto [l'articolo](https://developers.italia.it/it/news/2024/07/30/un-homeserver-matrix-per-la-community-di-developers-italia) in cui si annuncia l'avvio del servizio e si danno istruzioni per utilizzarlo. Ho scoperto di avere già un account matrix (non lo ricordavo) e utilizzato il client Element per accedere. Mi sono ritrovato iscritto già ad un paio di stanze (di cui una sperimentale attivata nel 2017 della mia comunità di appartenenza, Open Data Sicilia). Trovato tra gli spazi pubblici #developers-italia:developers.italia.it in cui ho chiesto di entrare ma, al pari dell'utilizzo del link diretto presente nell'articolo sopra citato, mi appare il riquadro del caricamento senza alcun risultato anche dopo parecchi minuti di attesa (rotellina che continua a girare accanto alla parola caricamento).

Ho provato a seguire le istruzioni per accedere con Thunderbird ma anche in questo caso nessun risultato.

**Comment by tensor5** [comment]
Grazie @picomiles per la segnalazione, il servizio è di nuovo in funzione.
